<a href="https://www.kaggle.com/code/landge0507/data-processing?scriptVersionId=215967975" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

 Libraries

In [1]:
import numpy as np 
import pandas as pd 


Loading the dataset

In [2]:
df =pd.read_csv('/kaggle/input/customer-shopping-latest-trends-dataset/shopping_trends.csv')

In [3]:
df

Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing   
1               2   19    Male        Sweater     Clothing   
2               3   50    Male          Jeans     Clothing   
3               4   21    Male        Sandals     Footwear   
4               5   45    Male         Blouse     Clothing   
...           ...  ...     ...            ...          ...   
3895         3896   40  Female         Hoodie     Clothing   
3896         3897   52  Female       Backpack  Accessories   
3897         3898   46  Female           Belt  Accessories   
3898         3899   44  Female          Shoes     Footwear   
3899         3900   52  Female        Handbag  Accessories   

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter   
1                        64          Maine    L     Maroon  Winter   
2                        73  Massachusetts    S     Maroon  Spring   
3                        90   Rhode Island    M     Maroon  Spring   
4                        49         Oregon    M  Turquoise  Spring   
...                     ...            ...  ...        ...     ...   
3895                     28       Virginia    L  Turquoise  Summer   
3896                     49           Iowa    L      White  Spring   
3897                     33     New Jersey    L      Green  Spring   
3898                     77      Minnesota    S      Brown  Summer   
3899                     81     California    M      Beige  Spring   

      Review Rating Subscription Status Payment Method   Shipping Type  \
0               3.1                 Yes    Credit Card         Express   
1               3.1                 Yes  Bank Transfer         Express   
2               3.1                 Yes           Cash   Free Shipping   
3               3.5                 Yes         PayPal    Next Day Air   
4               2.7                 Yes           Cash   Free Shipping   
...             ...                 ...            ...             ...   
3895            4.2                  No           Cash  2-Day Shipping   
3896            4.5                  No         PayPal    Store Pickup   
3897            2.9                  No    Credit Card        Standard   
3898            3.8                  No         PayPal         Express   
3899            3.1                  No  Bank Transfer    Store Pickup   

     Discount Applied Promo Code Used  Previous Purchases  \
0                 Yes             Yes                  14   
1                 Yes             Yes                   2   
2                 Yes             Yes                  23   
3                 Yes             Yes                  49   
4                 Yes             Yes                  31   
...               ...             ...                 ...   
3895               No              No                  32   
3896               No              No                  41   
3897               No              No                  24   
3898               No              No                  24   
3899               No              No                  33   

     Preferred Payment Method Frequency of Purchases  
0                       Venmo            Fortnightly  
1                        Cash            Fortnightly  
2                 Credit Card                 Weekly  
3                      PayPal                 Weekly  
4                      PayPal               Annually  
...                       ...                    ...  
3895                    Venmo                 Weekly  
3896            Bank Transfer              Bi-Weekly  
3897                    Venmo              Quarterly  
3898                    Venmo                 Weekly  
3899                    Venmo              Quarterly  

[3900 rows x 19 columns]

In [4]:
x=df[['Location','Age','Review Rating']]

In [5]:
x

Location  Age  Review Rating
0          Kentucky   55            3.1
1             Maine   19            3.1
2     Massachusetts   50            3.1
3      Rhode Island   21            3.5
4            Oregon   45            2.7
...             ...  ...            ...
3895       Virginia   40            4.2
3896           Iowa   52            4.5
3897     New Jersey   46            2.9
3898      Minnesota   44            3.8
3899     California   52            3.1

[3900 rows x 3 columns]

In [6]:
x=df[['Location','Age','Review Rating']].values

In [7]:
x

array([['Kentucky', 55, 3.1],
       ['Maine', 19, 3.1],
       ['Massachusetts', 50, 3.1],
       ...,
       ['New Jersey', 46, 2.9],
       ['Minnesota', 44, 3.8],
       ['California', 52, 3.1]], dtype=object)

In [8]:
y=df[['Previous Purchases']].values

In [9]:
y

array([[14],
       [ 2],
       [23],
       ...,
       [24],
       [24],
       [33]])

Finding the missing values from dataset

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [12]:
impute=imputer.fit(x[:,2:3])

In [13]:
x[:,2:3]=imputer.transform(x[:,2:3])

In [14]:
x

array([['Kentucky', 55, 3.1],
       ['Maine', 19, 3.1],
       ['Massachusetts', 50, 3.1],
       ...,
       ['New Jersey', 46, 2.9],
       ['Minnesota', 44, 3.8],
       ['California', 52, 3.1]], dtype=object)

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
label_encoder_x=LabelEncoder()

In [17]:
x[:,0]=label_encoder_x.fit_transform(x[:,0])

In [18]:
x

array([[16, 55, 3.1],
       [18, 19, 3.1],
       [20, 50, 3.1],
       ...,
       [29, 46, 2.9],
       [22, 44, 3.8],
       [4, 52, 3.1]], dtype=object)

In [19]:
label_encoder_x=LabelEncoder()

In [20]:
x[:,0]=label_encoder_x.fit_transform(x[:,0])

In [21]:
x

array([[16, 55, 3.1],
       [18, 19, 3.1],
       [20, 50, 3.1],
       ...,
       [29, 46, 2.9],
       [22, 44, 3.8],
       [4, 52, 3.1]], dtype=object)

Using dummy encoding

In [22]:
from sklearn.preprocessing import OneHotEncoder

In [23]:
onehotencoder=OneHotEncoder()

In [24]:
x=onehotencoder.fit_transform(df.Location.values.reshape(-1,1)).toarray()

In [25]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [26]:
labelencoder_y=LabelEncoder()

In [27]:
y=labelencoder_y.fit_transform(y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [28]:
y

array([13,  1, 22, ..., 23, 23, 32])

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [31]:
x_train

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [32]:
x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [33]:
type(x_test)

numpy.ndarray

In [34]:
y_train

array([16, 10,  3, ..., 28, 37, 26])

In [35]:
y_test

array([31, 39, 44, 25, 16,  2,  7, 13,  0,  9, 24, 20,  8, 27,  6, 35, 40,
        4, 37, 23, 42, 11, 12, 20, 14, 13, 39, 33,  2, 47, 32, 43, 45, 17,
       26, 46, 25, 38, 40, 31,  1, 36, 49, 38, 44,  1, 38, 19, 30, 32, 22,
       19, 24, 34, 38, 21, 23, 40,  0,  4, 46,  3, 23,  9, 33, 44, 12, 10,
       16, 10, 34,  9,  3, 10,  8, 12, 49,  7,  8, 13, 36, 36,  1, 11,  1,
       47,  8, 45, 26, 21, 24, 29, 48, 18, 10, 43, 45, 19, 32,  7, 45, 38,
       39, 13, 15, 21, 38, 17, 44, 32, 38, 19, 23,  3, 34, 22, 21, 29, 46,
       10,  0, 40, 32,  4, 41,  9,  1, 18, 49, 47, 39, 23, 30, 47, 47,  1,
       18, 32, 20,  0, 11, 24,  6, 44, 37,  5,  9, 27, 36, 25, 38,  0, 30,
        4, 34, 23, 47, 41,  6, 48, 28, 40,  8, 24, 49, 20,  4,  2, 13, 22,
       14, 46, 24, 21,  5,  7, 34, 22, 30, 30, 14, 38, 30, 18, 29, 17, 10,
       45, 11, 40, 32, 28,  0, 17, 30, 37,  9, 44, 33, 19, 37, 48, 24, 22,
       41, 19, 35,  6,  5, 41, 41, 12, 18, 33,  9, 43, 11, 26, 24, 17, 19,
       41, 24, 23, 32, 19

Feature Scaling

In [36]:
from sklearn.preprocessing import StandardScaler

In [37]:
sc_x=StandardScaler()

In [38]:
x_train=sc_x.fit_transform(x_train)

In [39]:
x_test=sc_x.transform(x_test)

In [40]:
x_train

array([[-0.15149528, -0.13883352, -0.12891001, ...,  6.80240599,
        -0.14002801, -0.13641557],
       [-0.15149528, -0.13883352, -0.12891001, ..., -0.14700681,
        -0.14002801, -0.13641557],
       [-0.15149528, -0.13883352, -0.12891001, ...,  6.80240599,
        -0.14002801, -0.13641557],
       ...,
       [-0.15149528, -0.13883352, -0.12891001, ..., -0.14700681,
        -0.14002801, -0.13641557],
       [-0.15149528, -0.13883352, -0.12891001, ..., -0.14700681,
        -0.14002801, -0.13641557],
       [-0.15149528, -0.13883352, -0.12891001, ..., -0.14700681,
        -0.14002801, -0.13641557]])

In [41]:
x_test

array([[-0.15149528, -0.13883352, -0.12891001, ..., -0.14700681,
        -0.14002801, -0.13641557],
       [-0.15149528, -0.13883352, -0.12891001, ..., -0.14700681,
        -0.14002801, -0.13641557],
       [-0.15149528, -0.13883352, -0.12891001, ...,  6.80240599,
        -0.14002801, -0.13641557],
       ...,
       [-0.15149528, -0.13883352, -0.12891001, ..., -0.14700681,
        -0.14002801, -0.13641557],
       [-0.15149528, -0.13883352, -0.12891001, ..., -0.14700681,
        -0.14002801, -0.13641557],
       [-0.15149528, -0.13883352,  7.75734946, ..., -0.14700681,
        -0.14002801, -0.13641557]])