<a href="https://www.kaggle.com/code/landge0507/numpy?scriptVersionId=215967655" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np 

In [2]:
np.array([3.2,4,5,6])

array([3.2, 4. , 5. , 6. ])

In [3]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [4]:
np.array([2,3,4,5,6], dtype="str")

array(['2', '3', '4', '5', '6'], dtype='<U1')

In [5]:
np.array([2,3,4,5,6], dtype="float32")

array([2., 3., 4., 5., 6.], dtype=float32)

In [6]:
np.array([range(i,i+3) for i in[2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [7]:
np.zeros(10, dtype="int") 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.zeros((5,6), dtype="float")

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,5), dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [11]:
np.arange(0,22,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Standerd scaler
imputer

In [12]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.random.random((3,3))

array([[0.70227995, 0.7140583 , 0.28366762],
       [0.10181784, 0.76205127, 0.30578332],
       [0.01082093, 0.59319654, 0.20591704]])

In [14]:
np.random.normal(1,10,(3,3))

array([[  2.95801886,  -7.24508583,   8.0864825 ],
       [ -8.23930589,  -2.04773535,   1.88378572],
       [-11.13873271,   0.36154103,   2.80980353]])

In [15]:
np.random.randint(0,10,(3,3))

array([[5, 4, 5],
       [0, 5, 5],
       [5, 4, 8]])

In [16]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.empty((3,3),dtype="int")

array([[4607182418800017408,                   0,                   0],
       [                  0, 4607182418800017408,                   0],
       [                  0,                   0, 4607182418800017408]])

In [18]:
np.zeros(10,dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [19]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

NumPy Array Attributes

In [20]:
np.random.seed(0) 
x1 = np.random.randint(10, size=6)

In [21]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  
x2 = np.random.randint(10, size=(3,4)) 
x3 = np.random.randint(10, size=(3,4,5)) 

print("x1 ndim: ",x1.ndim)
print("x1 shape: ",x1.shape)
print("x1 size: ",x1.size) 

print("x1 ndim: ",x2.ndim)
print("x1 shape: ",x2.shape)
print("x1 size: ",x2.size) 

print("x1 ndim: ",x3.ndim)
print("x1 shape: ",x3.shape)
print("x1 size: ",x3.size)

print("dtype: ",x1.dtype) 
print("itemsize:",x1.itemsize,"bytes")
print("nbytes:",x1.nbytes,"bytes")

print("dtype: ",x2.dtype) 
print("itemsize:",x2.itemsize,"bytes")
print("nbytes:",x2.nbytes,"bytes")

print("dtype: ",x3.dtype) 
print("itemsize:",x3.itemsize,"bytes")
print("nbytes:",x3.nbytes,"bytes")

x1 ndim:  1
x1 shape:  (6,)
x1 size:  6
x1 ndim:  2
x1 shape:  (3, 4)
x1 size:  12
x1 ndim:  3
x1 shape:  (3, 4, 5)
x1 size:  60
dtype:  int64
itemsize: 8 bytes
nbytes: 48 bytes
dtype:  int64
itemsize: 8 bytes
nbytes: 96 bytes
dtype:  int64
itemsize: 8 bytes
nbytes: 480 bytes


In [22]:
x1[0]

5

In [23]:
x1[5]

9

In [24]:
x1[-1]

9

In [25]:
x1[-2]

7

In [26]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [27]:
x2[2,1]

6

In [28]:
x2[2,0]

1

In [29]:
x2[2,-4]

1

In [30]:
x2[-3,-4]

3

In [31]:
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [32]:
x1

array([5, 0, 3, 3, 7, 9])

In [33]:
x1[0]=3.141509
x1

array([3, 0, 3, 3, 7, 9])


Array Slicing: Accessing Subarrays

In [34]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
x[5:]

array([5, 6, 7, 8, 9])

In [36]:
x[:5]

array([0, 1, 2, 3, 4])

In [37]:
x[4:7]

array([4, 5, 6])

In [38]:
x[::2]

array([0, 2, 4, 6, 8])

In [39]:
x[1::2]

array([1, 3, 5, 7, 9])

In [40]:
x[-7:-2:2]

array([3, 5, 7])

In [41]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [42]:
x[5::-2]

array([5, 3, 1])

In [43]:
x[5:1:-2]

array([5, 3])

In [44]:
x[5:-8:-2]

array([5, 3])

In [45]:
x[7:-6:-1]

array([7, 6, 5])

In [46]:
x[-7:-8:-1]

array([3])

Multidimensional subarrays

In [47]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [48]:
x2[:3,:2]

array([[12,  5],
       [ 7,  6],
       [ 1,  6]])

In [49]:
x2[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [50]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [51]:
print(x2[:, 0])

[12  7  1]


In [52]:
print(x2[0,:])

[12  5  2  4]


In [53]:
print(x2[0])

[12  5  2  4]


Subarrays as no-copy views

In [54]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [55]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [56]:
x2_sub [0,0] = 99
x2_sub

array([[99,  5],
       [ 7,  6]])

In [57]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [58]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [59]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [60]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Reshaping of Arrays

In [61]:
grid = np.arange(1,10,1).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [62]:
x = np.array([1, 2, 3])
x.shape

(3,)

In [63]:
x.reshape(1,3).shape

(1, 3)

In [64]:
x[np.newaxis, :].shape

(1, 3)

In [65]:
x.reshape(1,-1).shape

(1, 3)

In [66]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [67]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [68]:
x.reshape(-1,1).shape

(3, 1)

In [69]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate((x, y))

array([1, 2, 3, 3, 2, 1])

In [70]:
z = np.array([99,99,99]) 
print(np.concatenate((x,y,z)))

[ 1  2  3  3  2  1 99 99 99]


In [71]:
grip = np.array([[1,2,3],
           [4,5,6]])

In [72]:
np.concatenate((grid,grid))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])